var greater = 3 > 1;
var greater2 = 3 < 1;
var less = 5 <= 8;
var less2 = 5 >= 8;
var greaterequal = 5 == 5;
console.log(greater);
console.log(greater2);
console.log(less);
console.log(less2);
console.log(greaterequal);